{
 "title": "Temperature Sensor Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "sensor", "query": "1, 2, 3, 4, 5, 6, 7, 8, 9, 10" }
  ]
 },
 "panels": [
  {
   "title": "Temp heat grid",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "temperature_readings",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg temp/sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature_readings",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "5s avg",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature_readings",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Max temp",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "temperature_readings",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sensor pressure last 60s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "sensor_pressure",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 14, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "temperature_readings",
     "query": "SELECT mean(\"temperature\") FROM \"5s_temp_avg\" WHERE $timeFilter GROUP BY time(1h), \"sensor\" fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Smoke alerts",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "smoke_alerts",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}